on:
    push:
        branches:
        - main
jobs:
    drata-iac-scan:
        runs-on: ubuntu-latest
        name: compliance-as-code-action
        steps:
        - uses: actions/checkout@v4
        - uses: drata/compliance-as-code-action@v1.0.0
            env:
                DRATA_API_TOKEN: ${{ secrets.DRATA_IAC_PIPELINE_KEY }}
                GITHUB_REPOSITORY: $GITHUB_REPOSITORY
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            with:
                minimumSeverity: 'NONE'